//! Tier-3 — perceptual diff for processed TIFF/DNG.
//!
//! TIFF and DNG output ride on top of the highlight-recovery code that the
//! user actively iterates on. A naive MD5 comparison would force a hash
//! refresh on every algorithm tweak and conflate noise (intentional drift)
//! with signal (regressions in unrelated stages).
//!
//! Instead we compare two 16-bit RGB rasters channel-by-channel and assert
//! statistical bounds:
//!
//! - **max_abs_diff** caps how far any single channel sample can drift.
//! - **fraction_over_8** caps how *many* channel samples can drift even by
//!   ±8 LSB (out of 65535).
//!
//! Today's checks are tight bounds — they're really self-consistency tests:
//! converting the same input twice must produce *exactly* the same pixels
//! (max_abs_diff == 0). This catches non-deterministic ordering bugs that
//! creep in once we add rayon parallelism in M7. As the pipeline ports
//! progress, additional cases will compare against committed-side goldens
//! generated by the legacy C binary; for now, the harness is in place and
//! the goldens slot is documented as a future addition (see tests/README).
//!
//! Tier-3 deliberately does not check ΔE2000 yet. The current pipeline runs
//! in linear-light 16-bit space and per-channel epsilon catches everything
//! ΔE would flag, without dragging in a CIE color-conversion dep. ΔE comes
//! back when M6 introduces device-independent color comparisons.

mod common;

use std::fs;
use std::path::Path;

use common::{image_diff, read_tiff_rgb16, run_extract, RgbImage};

const MERRILL_INPUT: &str = "sigma_sd1_merrill_10.x3f";
const MERRILL_REAL: &str = "DP2M0768.X3F";
const QUATTRO_REAL: &str = "DP0Q0010.X3F";

/// Two consecutive `-tiff` runs against the same input must produce
/// pixel-identical output. Catches non-determinism (uninitialised reads,
/// non-deterministic iteration order under parallelism).
#[test]
fn merrill_tiff_is_deterministic() {
    let input = skip_if_missing!(MERRILL_INPUT);
    let switches = &["-tiff", "-no-denoise", "-color", "none", "-no-crop"];

    let a = run_extract(&input, switches, ".tif");
    let img_a = read_tiff_rgb16(&a);
    let b = run_extract(&input, switches, ".tif");
    let img_b = read_tiff_rgb16(&b);

    let diff = image_diff(&img_a, &img_b);
    assert_eq!(
        diff.max_abs_diff, 0,
        "TIFF output is non-deterministic ({} channel samples differ, max abs {})",
        diff.samples_over_8, diff.max_abs_diff
    );
}

/// A `-color sRGB -compress` TIFF run must match an uncompressed run after
/// decoding — the compression switch shouldn't perturb pixel values, only
/// the on-disk encoding. Documents the expectation as a regression gate.
#[test]
fn merrill_tiff_compress_is_lossless() {
    let input = skip_if_missing!(MERRILL_INPUT);
    let raw = run_extract(&input, &["-tiff", "-no-denoise", "-color", "sRGB"], ".tif");
    let zip = run_extract(
        &input,
        &["-tiff", "-no-denoise", "-color", "sRGB", "-compress"],
        ".tif",
    );
    let raw_img = read_tiff_rgb16(&raw);
    let zip_img = read_tiff_rgb16(&zip);
    let diff = image_diff(&raw_img, &zip_img);
    assert_eq!(
        diff.max_abs_diff, 0,
        "compressed TIFF differs from uncompressed: {diff:?}"
    );
}

/// Two `-dng` runs are pixel-identical (DNG raster is uncompressed linear
/// 16-bit RGB; the decoder path is the same as for TIFF).
#[test]
fn merrill_dng_is_deterministic() {
    let input = skip_if_missing!(MERRILL_INPUT);
    let switches = &["-dng", "-no-denoise"];
    let a = run_extract(&input, switches, ".dng");
    let img_a = read_tiff_rgb16(&a);
    let b = run_extract(&input, switches, ".dng");
    let img_b = read_tiff_rgb16(&b);
    let diff = image_diff(&img_a, &img_b);
    assert_eq!(
        diff.max_abs_diff, 0,
        "DNG output is non-deterministic: {diff:?}"
    );
}

/// `-tiff -unprocessed` skips colour-space conversion and gamma. The output
/// must be deterministic and structurally well-formed (non-empty, plausible
/// channel range — never all-zero or all-saturated).
#[test]
fn merrill_unprocessed_tiff_has_signal() {
    let input = skip_if_missing!(MERRILL_INPUT);
    let out = run_extract(
        &input,
        &["-tiff", "-no-denoise", "-unprocessed", "-no-crop"],
        ".tif",
    );
    let img = read_tiff_rgb16(&out);
    assert!(img.width > 0 && img.height > 0, "empty image");
    assert_eq!(
        img.pixels.len(),
        img.width as usize * img.height as usize * 3,
        "interleaved RGB pixel count mismatch"
    );
    let (min, max) = channel_extents(&img);
    assert!(
        max > min + 100,
        "unprocessed TIFF has near-uniform pixel values (min={min}, max={max}); RAW load likely failed"
    );
}

/// Two `-dng` runs must produce pixel-identical raw planes.
///
/// `merrill_dng_is_deterministic` (above) compares the IFD0 preview via
/// `read_tiff_rgb16` (which reads `seek_to_image(0)`); this test reaches
/// into the SubIFD raw plane to catch non-determinism in the processing
/// pipeline that wouldn't show up in the downsampled preview. Important
/// after we cut over to the Rust DNG writer — we lost the libtiff
/// baseline and rely on self-consistency for raw-plane regression
/// coverage until tier-3 goldens are committed.
#[test]
fn dng_raw_plane_is_deterministic() {
    let input = skip_if_missing!(MERRILL_REAL);
    let switches = &["-dng", "-no-denoise"];
    let a = run_extract(&input, switches, ".dng");
    let img_a = read_dng_raw_ifd(&a);
    let b = run_extract(&input, switches, ".dng");
    let img_b = read_dng_raw_ifd(&b);
    let diff = image_diff(&img_a, &img_b);
    assert_eq!(
        diff.max_abs_diff, 0,
        "DNG raw plane is non-deterministic on {MERRILL_REAL}: {diff:?}"
    );
}

/// Same as `dng_raw_plane_is_deterministic` but for a Quattro file. Exercises
/// the M5a Rust port of `x3f_expand_quattro` — the bicubic upsample uses
/// pre-computed weight tables and per-channel deinterleave/reinterleave
/// loops that would expose any nondeterminism (e.g. accidental rayon
/// par_iter without an ordered fold).
#[test]
fn quattro_dng_raw_plane_is_deterministic() {
    let input = skip_if_missing!(QUATTRO_REAL);
    let switches = &["-dng", "-no-denoise"];
    let a = run_extract(&input, switches, ".dng");
    let img_a = read_dng_raw_ifd(&a);
    let b = run_extract(&input, switches, ".dng");
    let img_b = read_dng_raw_ifd(&b);
    let diff = image_diff(&img_a, &img_b);
    assert_eq!(
        diff.max_abs_diff, 0,
        "Quattro DNG raw plane is non-deterministic on {QUATTRO_REAL}: {diff:?}"
    );
}

/// Quattro `-dng` output should have plausible pixel values across the full
/// frame after expansion. Specifically, the upsampled BMT image should not
/// be all-zero or all-saturated, and the channel range should span more
/// than ~100 LSB. Catches the case where `x3f_expand_quattro` returns
/// without populating `expanded` (the M0 stub `exit(2)`'d; a regression
/// here would be e.g. an off-by-one stride error producing rows of zeros).
///
/// `-no-crop` gives this test a different switch fingerprint from
/// `quattro_dng_raw_plane_is_deterministic` so the test harness picks a
/// distinct scratch dir and they don't race when run in parallel.
#[test]
fn quattro_dng_raw_plane_has_signal() {
    let input = skip_if_missing!(QUATTRO_REAL);
    let out = run_extract(&input, &["-dng", "-no-denoise", "-no-crop"], ".dng");
    let img = read_dng_raw_ifd(&out);
    assert!(img.width > 0 && img.height > 0);
    let (min, max) = channel_extents(&img);
    assert!(
        max > min + 100,
        "Quattro raw plane has near-uniform values (min={min}, max={max}); expand_quattro likely no-op'd"
    );
}

/// Read the DNG raw plane. Both the legacy libtiff path and the new Rust
/// writer place the raw IFD in `IFD0.SubIFDs[0]` and leave the IFD0 →
/// IFD1 chain link at 0. The `tiff` crate's `seek_to_image` walks the
/// chain link and so doesn't reach the raw plane — we walk SubIFDs by
/// hand and decode the strips ourselves. The format is always
/// uncompressed 16-bit RGB for our test invocations (no `-compress`).
fn read_dng_raw_ifd(path: &Path) -> RgbImage {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("read `{}`: {e}", path.display()));
    assert_eq!(&bytes[..2], b"II", "DNG must be little-endian");
    assert_eq!(read_u16(&bytes, 2), 42, "TIFF magic mismatch");
    let ifd0_off = read_u32(&bytes, 4) as usize;
    let raw_ifd_off = read_subifd0_offset(&bytes, ifd0_off);
    let raw_ifd = parse_ifd(&bytes, raw_ifd_off);

    let width = first_long_or_short(&bytes, &raw_ifd, 256);
    let height = first_long_or_short(&bytes, &raw_ifd, 257);
    let bits_per_sample = first_long_or_short(&bytes, &raw_ifd, 258);
    let samples_per_pixel = first_long_or_short(&bytes, &raw_ifd, 277);
    assert_eq!(bits_per_sample, 16, "raw IFD must be 16-bit");
    assert_eq!(samples_per_pixel, 3, "raw IFD must be 3-channel");
    let compression = first_long_or_short(&bytes, &raw_ifd, 259);
    assert_eq!(compression, 1, "test expects uncompressed raw plane");

    let strip_offsets = read_long_or_short_vec(&bytes, &raw_ifd, 273);
    let strip_byte_counts = read_long_or_short_vec(&bytes, &raw_ifd, 279);
    assert_eq!(strip_offsets.len(), strip_byte_counts.len());

    let mut pixels: Vec<u16> =
        Vec::with_capacity((width as usize) * (height as usize) * (samples_per_pixel as usize));
    for (off, len) in strip_offsets.iter().zip(strip_byte_counts.iter()) {
        let strip = &bytes[*off as usize..(*off as usize) + (*len as usize)];
        for chunk in strip.chunks_exact(2) {
            pixels.push(u16::from_le_bytes([chunk[0], chunk[1]]));
        }
    }
    RgbImage {
        width,
        height,
        pixels,
    }
}

fn read_u16(b: &[u8], off: usize) -> u16 {
    u16::from_le_bytes([b[off], b[off + 1]])
}
fn read_u32(b: &[u8], off: usize) -> u32 {
    u32::from_le_bytes([b[off], b[off + 1], b[off + 2], b[off + 3]])
}

#[derive(Clone)]
struct IfdEntry {
    tag: u16,
    typ: u16,
    count: u32,
    /// Either the inline 4-byte payload or the file offset of the payload.
    raw_value: [u8; 4],
}

fn parse_ifd(bytes: &[u8], off: usize) -> Vec<IfdEntry> {
    let count = read_u16(bytes, off) as usize;
    let mut entries = Vec::with_capacity(count);
    let base = off + 2;
    for i in 0..count {
        let p = base + i * 12;
        entries.push(IfdEntry {
            tag: read_u16(bytes, p),
            typ: read_u16(bytes, p + 2),
            count: read_u32(bytes, p + 4),
            raw_value: [bytes[p + 8], bytes[p + 9], bytes[p + 10], bytes[p + 11]],
        });
    }
    entries
}

fn read_subifd0_offset(bytes: &[u8], ifd0_off: usize) -> usize {
    let ifd0 = parse_ifd(bytes, ifd0_off);
    let entry = ifd0
        .iter()
        .find(|e| e.tag == 330)
        .expect("DNG IFD0 missing SubIFDs tag");
    // SubIFDs is a LONG[N]. With N=1 it fits inline.
    if entry.count == 1 {
        u32::from_le_bytes(entry.raw_value) as usize
    } else {
        let off = u32::from_le_bytes(entry.raw_value) as usize;
        read_u32(bytes, off) as usize
    }
}

fn first_long_or_short(bytes: &[u8], ifd: &[IfdEntry], tag: u16) -> u32 {
    read_long_or_short_vec(bytes, ifd, tag)[0]
}

fn read_long_or_short_vec(bytes: &[u8], ifd: &[IfdEntry], tag: u16) -> Vec<u32> {
    let entry = ifd
        .iter()
        .find(|e| e.tag == tag)
        .unwrap_or_else(|| panic!("raw IFD missing tag {tag}"));
    let element_size = match entry.typ {
        3 => 2,
        4 => 4,
        other => panic!("tag {tag} has unexpected type {other}"),
    };
    let total_size = (entry.count as usize) * element_size;
    let payload: &[u8] = if total_size <= 4 {
        &entry.raw_value[..total_size]
    } else {
        let off = u32::from_le_bytes(entry.raw_value) as usize;
        &bytes[off..off + total_size]
    };
    match entry.typ {
        3 => payload
            .chunks_exact(2)
            .map(|c| u16::from_le_bytes([c[0], c[1]]) as u32)
            .collect(),
        4 => payload
            .chunks_exact(4)
            .map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect(),
        _ => unreachable!(),
    }
}

fn channel_extents(img: &RgbImage) -> (u16, u16) {
    let mut min = u16::MAX;
    let mut max = 0u16;
    for &p in &img.pixels {
        if p < min {
            min = p;
        }
        if p > max {
            max = p;
        }
    }
    (min, max)
}
