//! Minimal ICC v2 input-profile assembler — used by the cineon-log TIFF
//! writer to tag pixels with their primaries while leaving the log
//! encoding curve **unreversed** by colour-managed readers.
//!
//! The TIFF spec lets us drop an ICC profile blob into tag 34675; readers
//! that honour it (DaVinci, Capture One, Premiere, Lightroom, Photoshop)
//! consult it for the file's interpretation. We ship the matrix-shaped
//! variant of an ICC v2 profile with three primary-XYZ tags, three
//! identical TRC curves of `count = 0` (linear identity), plus the
//! required `desc`/`cprt`/`wtpt` housekeeping. About 380 bytes per profile.
//!
//! Why a *linear* TRC on log-encoded pixels: a cineon log file is meant
//! to look flat in viewers and be graded by an explicit input transform
//! the colourist applies in their NLE/grading app (Resolve, Premiere,
//! Capture One). If we sampled the inverse log into the TRC, ICC-aware
//! viewers would round-trip the encoding back to scene-linear and the
//! file would visually match a plain linear TIFF — the opposite of what
//! "flat for grading" means in practice. Embedding a linear TRC tells
//! readers "treat the data as already-linear within these primaries",
//! so the file looks flat in any viewer and the colourist owns the
//! decode step.
//!
//! References:
//!   - ICC.1:2001-04 (v2), §6 "Profile structure" + §6.4 "Tag definitions".
//!   - ICC v4 §B.4 "Use of D50" — explains the D50 PCS clamp that forces
//!     us to ship Bradford-adapted primaries for sRGB/AdobeRGB while
//!     ProPhoto's already-D50 primaries pass through unchanged.
//!
//! The primary-XYZ constants below are the published D50-adapted values
//! used by Adobe's reference profiles; we hard-code rather than recompute
//! at runtime so that for a given `scale` the TIFF byte stream is bit-
//! stable across builds.

use crate::ColorEncoding;

/// Build a cineon-log ICC v2 profile for `encoding`. The TRC tables are a
/// linear identity (`count = 0`) so colour-managed readers do not invert
/// the log curve back to scene-linear; the file looks flat in any viewer
/// and the colourist applies their own input transform when grading.
///
/// Returns `None` for encodings without a defined color space (`None`,
/// `Unprocessed`, `Qtop`); the TIFF writer just skips the `ICCProfile`
/// tag in that case (camera-native log dump).
pub fn cineon_log_profile(encoding: ColorEncoding) -> Option<Vec<u8>> {
    let primaries = match encoding {
        ColorEncoding::Srgb => &SRGB_PRIMARIES,
        ColorEncoding::AdobeRgb => &ADOBE_RGB_PRIMARIES,
        ColorEncoding::ProPhotoRgb => &PROPHOTO_RGB_PRIMARIES,
        ColorEncoding::None | ColorEncoding::Unprocessed | ColorEncoding::Qtop => return None,
    };
    Some(assemble(primaries))
}

/// Description text + the three D50-adapted primary XYZ tristimuli that
/// distinguish one cineon-log RGB profile from another.
struct ProfileSpec {
    desc: &'static str,
    /// (X, Y, Z) for the red primary, D50-adapted.
    r_xyz: [f64; 3],
    g_xyz: [f64; 3],
    b_xyz: [f64; 3],
}

// D50-adapted (Bradford) primaries for the IEC 61966-2-1 sRGB color space.
// Sourced from the ICC sRGB v4 reference profile and Adobe's published
// reference values.
const SRGB_PRIMARIES: ProfileSpec = ProfileSpec {
    desc: "x3f Cineon-Log sRGB",
    r_xyz: [0.4360747, 0.2225045, 0.0139322],
    g_xyz: [0.3850649, 0.7168786, 0.0971045],
    b_xyz: [0.1430804, 0.0606169, 0.7141733],
};

// D50-adapted (Bradford) primaries for Adobe RGB (1998).
const ADOBE_RGB_PRIMARIES: ProfileSpec = ProfileSpec {
    desc: "x3f Cineon-Log Adobe RGB (1998)",
    r_xyz: [0.6097559, 0.3111242, 0.0194811],
    g_xyz: [0.2052401, 0.6256560, 0.0608902],
    b_xyz: [0.1492240, 0.0632197, 0.7448387],
};

// ProPhoto RGB (ROMM RGB) is natively D50, so no chromatic adaptation is
// applied. Values from ANSI/I3A IT10.7666:2002.
const PROPHOTO_RGB_PRIMARIES: ProfileSpec = ProfileSpec {
    desc: "x3f Cineon-Log ProPhoto RGB",
    r_xyz: [0.7976749, 0.2880402, 0.0000000],
    g_xyz: [0.1351917, 0.7118741, 0.0000000],
    b_xyz: [0.0313534, 0.0000857, 0.8252100],
};

const COPYRIGHT: &str = "Public Domain — generated by x3f_extract";

// Spec D50 illuminant in s15Fixed16: (0.9642, 1.0000, 0.8249).
const D50_X: i32 = 0x0000_F6D6;
const D50_Y: i32 = 0x0001_0000;
const D50_Z: i32 = 0x0000_D32D;

// Tag signatures (4-char ASCII).
const SIG_DESC: [u8; 4] = *b"desc";
const SIG_CPRT: [u8; 4] = *b"cprt";
const SIG_WTPT: [u8; 4] = *b"wtpt";
const SIG_RXYZ: [u8; 4] = *b"rXYZ";
const SIG_GXYZ: [u8; 4] = *b"gXYZ";
const SIG_BXYZ: [u8; 4] = *b"bXYZ";
const SIG_RTRC: [u8; 4] = *b"rTRC";
const SIG_GTRC: [u8; 4] = *b"gTRC";
const SIG_BTRC: [u8; 4] = *b"bTRC";

fn assemble(p: &ProfileSpec) -> Vec<u8> {
    // Build the tag bodies first so we know each one's offset and size,
    // then prepend the header + tag table.
    let desc_body = build_desc(p.desc);
    let cprt_body = build_text(COPYRIGHT);
    let wtpt_body = build_xyz(D50_X, D50_Y, D50_Z);
    let rxyz_body = build_xyz_f(&p.r_xyz);
    let gxyz_body = build_xyz_f(&p.g_xyz);
    let bxyz_body = build_xyz_f(&p.b_xyz);
    let trc_body = build_linear_curve();

    // The three TRC tags share one body — same bytes, one offset. The
    // ICC spec explicitly permits this and Photoshop's reference encoder
    // does it.
    let bodies: &[(&[u8; 4], &[u8])] = &[
        (&SIG_DESC, &desc_body),
        (&SIG_CPRT, &cprt_body),
        (&SIG_WTPT, &wtpt_body),
        (&SIG_RXYZ, &rxyz_body),
        (&SIG_GXYZ, &gxyz_body),
        (&SIG_BXYZ, &bxyz_body),
    ];

    let header_len: u32 = 128;
    let tag_count: u32 = (bodies.len() as u32) + 3; // + rTRC/gTRC/bTRC
    let table_len: u32 = 4 + tag_count * 12;
    let mut next_offset = header_len + table_len;

    // First pass: compute (sig, offset, size) for each tag, padding each
    // body to a 4-byte boundary as the spec requires.
    let mut entries: Vec<([u8; 4], u32, u32)> = Vec::with_capacity(tag_count as usize);
    let mut combined: Vec<u8> = Vec::new();
    for (sig, body) in bodies {
        let off = next_offset;
        let size = body.len() as u32;
        entries.push((**sig, off, size));
        combined.extend_from_slice(body);
        let pad = (4 - (size as usize % 4)) % 4;
        combined.extend(std::iter::repeat_n(0u8, pad));
        next_offset += size + pad as u32;
    }
    let trc_off = next_offset;
    let trc_size = trc_body.len() as u32;
    combined.extend_from_slice(&trc_body);
    let trc_pad = (4 - (trc_size as usize % 4)) % 4;
    combined.extend(std::iter::repeat_n(0u8, trc_pad));
    entries.push((SIG_RTRC, trc_off, trc_size));
    entries.push((SIG_GTRC, trc_off, trc_size));
    entries.push((SIG_BTRC, trc_off, trc_size));

    let total_size = (header_len + table_len) as usize + combined.len();

    let mut out = Vec::with_capacity(total_size);
    write_header(&mut out, total_size as u32);
    write_u32(&mut out, tag_count);
    for (sig, off, size) in &entries {
        out.extend_from_slice(sig);
        write_u32(&mut out, *off);
        write_u32(&mut out, *size);
    }
    out.extend_from_slice(&combined);
    debug_assert_eq!(out.len(), total_size);
    out
}

fn write_header(out: &mut Vec<u8>, total_size: u32) {
    write_u32(out, total_size); // profile size
    write_u32(out, 0); // preferred CMM (none)
    write_u32(out, 0x0210_0000); // ICC v2.1.0 — widely accepted, no v4 surprises
    out.extend_from_slice(b"mntr"); // device class: display
    out.extend_from_slice(b"RGB "); // data color space
    out.extend_from_slice(b"XYZ "); // PCS
                                    // dateTime: 12 bytes of u16 BE (year, month, day, hour, minute, second).
                                    // Hard-coded to a fixed epoch so the output is bit-stable.
    write_u16(out, 2026);
    write_u16(out, 1);
    write_u16(out, 1);
    write_u16(out, 0);
    write_u16(out, 0);
    write_u16(out, 0);
    out.extend_from_slice(b"acsp"); // magic signature
    write_u32(out, 0); // platform
    write_u32(out, 0); // flags
    write_u32(out, 0); // manufacturer
    write_u32(out, 0); // model
    write_u64(out, 0); // attributes
    write_u32(out, 0); // rendering intent: perceptual
    write_i32(out, D50_X); // PCS illuminant X
    write_i32(out, D50_Y); // PCS illuminant Y
    write_i32(out, D50_Z); // PCS illuminant Z
    write_u32(out, 0); // creator
                       // 16 bytes profile-ID (left as zero — readers treat 0x00.. as "absent")
                       // + 28 bytes reserved.
    out.extend(std::iter::repeat_n(0u8, 16 + 28));
}

/// Build a `desc` tag body using the v2 `textDescriptionType`. Holds an
/// ASCII copy + an empty Unicode/ScriptCode tail (the bare minimum that
/// every reader I've seen accepts).
fn build_desc(s: &str) -> Vec<u8> {
    let bytes = s.as_bytes();
    let ascii_count = bytes.len() as u32 + 1; // +1 for the NUL
    let mut v = Vec::new();
    v.extend_from_slice(b"desc");
    write_u32(&mut v, 0); // reserved
    write_u32(&mut v, ascii_count);
    v.extend_from_slice(bytes);
    v.push(0); // NUL
    write_u32(&mut v, 0); // Unicode language code
    write_u32(&mut v, 0); // Unicode count
    v.push(0); // ScriptCode code
    v.push(0); // ScriptCode count
    v.extend(std::iter::repeat_n(0u8, 67)); // Macintosh ScriptCode body
    v
}

/// Build a `cprt` (or any v2 plain-text) tag body.
fn build_text(s: &str) -> Vec<u8> {
    let mut v = Vec::new();
    v.extend_from_slice(b"text");
    write_u32(&mut v, 0); // reserved
    v.extend_from_slice(s.as_bytes());
    v.push(0); // NUL terminator
    v
}

/// Build an `XYZType` body from raw s15Fixed16 components.
fn build_xyz(x: i32, y: i32, z: i32) -> Vec<u8> {
    let mut v = Vec::new();
    v.extend_from_slice(b"XYZ ");
    write_u32(&mut v, 0); // reserved
    write_i32(&mut v, x);
    write_i32(&mut v, y);
    write_i32(&mut v, z);
    v
}

/// Convenience wrapper: take an `[X, Y, Z]` triplet in float and convert
/// to s15Fixed16. The clamp covers the +/-32k limits of the encoding;
/// in practice every primary tristimulus we ship is well inside [0, 1].
fn build_xyz_f(xyz: &[f64; 3]) -> Vec<u8> {
    build_xyz(
        f_to_s15f16(xyz[0]),
        f_to_s15f16(xyz[1]),
        f_to_s15f16(xyz[2]),
    )
}

/// `curveType` body with `count = 0` — the spec's encoding for "linear
/// (identity) response from 0 to 1". This is *not* a description of the
/// pixel data; the pixels are log-encoded by the conversion LUT. The
/// linear TRC tells colour-managed readers to leave them alone, so the
/// log shape stays visible (lifted shadows, pulled highlights, flat
/// midtones) and the colourist applies an explicit input transform when
/// grading.
fn build_linear_curve() -> Vec<u8> {
    let mut v = Vec::new();
    v.extend_from_slice(b"curv");
    write_u32(&mut v, 0); // reserved
    write_u32(&mut v, 0); // count = 0 → linear identity
    v
}

fn f_to_s15f16(x: f64) -> i32 {
    let v = (x * 65536.0).round();
    v.clamp(i32::MIN as f64, i32::MAX as f64) as i32
}

fn write_u16(out: &mut Vec<u8>, v: u16) {
    out.extend_from_slice(&v.to_be_bytes());
}
fn write_u32(out: &mut Vec<u8>, v: u32) {
    out.extend_from_slice(&v.to_be_bytes());
}
fn write_i32(out: &mut Vec<u8>, v: i32) {
    out.extend_from_slice(&v.to_be_bytes());
}
fn write_u64(out: &mut Vec<u8>, v: u64) {
    out.extend_from_slice(&v.to_be_bytes());
}

#[cfg(test)]
mod tests {
    use super::*;

    fn read_u32(b: &[u8], off: usize) -> u32 {
        u32::from_be_bytes(b[off..off + 4].try_into().unwrap())
    }

    fn find_tag_offset(p: &[u8], sig: &[u8; 4]) -> Option<u32> {
        let tag_count = read_u32(p, 128) as usize;
        for i in 0..tag_count {
            let entry = 128 + 4 + i * 12;
            if &p[entry..entry + 4] == sig {
                return Some(read_u32(p, entry + 4));
            }
        }
        None
    }

    #[test]
    fn cineon_profiles_present_for_each_named_space() {
        for enc in [
            ColorEncoding::Srgb,
            ColorEncoding::AdobeRgb,
            ColorEncoding::ProPhotoRgb,
        ] {
            let p = cineon_log_profile(enc).unwrap_or_else(|| panic!("no profile for {enc:?}"));
            // Header: byte[36..40] is the 'acsp' magic.
            assert_eq!(&p[36..40], b"acsp", "magic missing for {enc:?}");
            // Header: byte[16..20] is colorSpace = 'RGB '.
            assert_eq!(&p[16..20], b"RGB ");
            // Header: byte[20..24] is PCS = 'XYZ '.
            assert_eq!(&p[20..24], b"XYZ ");
            // The first 4 bytes equal the profile size and match Vec len.
            assert_eq!(read_u32(&p, 0) as usize, p.len());
        }
    }

    #[test]
    fn no_profile_for_undefined_color_spaces() {
        assert!(cineon_log_profile(ColorEncoding::None).is_none());
        assert!(cineon_log_profile(ColorEncoding::Unprocessed).is_none());
        assert!(cineon_log_profile(ColorEncoding::Qtop).is_none());
    }

    #[test]
    fn srgb_primaries_match_spec_d50_values() {
        let p = cineon_log_profile(ColorEncoding::Srgb).unwrap();
        let off = find_tag_offset(&p, b"rXYZ").expect("rXYZ tag missing") as usize;
        assert_eq!(&p[off..off + 4], b"XYZ ");
        let x = i32::from_be_bytes(p[off + 8..off + 12].try_into().unwrap()) as f64 / 65536.0;
        assert!((x - 0.4360747).abs() < 1e-4, "got x = {x}");
    }

    #[test]
    fn rgb_trc_tags_are_linear_identity() {
        // Each TRC tag holds curveType with `count = 0`, the ICC v2
        // encoding for "linear identity". Colour-managed readers will
        // therefore display the log-encoded pixels as-is — that's the
        // whole point of cineon mode (flat for grading).
        let p = cineon_log_profile(ColorEncoding::Srgb).unwrap();
        for sig in [b"rTRC", b"gTRC", b"bTRC"] {
            let off = find_tag_offset(&p, sig).expect("TRC tag missing") as usize;
            assert_eq!(&p[off..off + 4], b"curv");
            let count = read_u32(&p, off + 8);
            assert_eq!(count, 0, "{sig:?} is not linear (count={count})");
        }
    }

    #[test]
    fn rgb_trc_tags_share_one_body() {
        // The three TRC tags are required to point at the same offset.
        let p = cineon_log_profile(ColorEncoding::Srgb).unwrap();
        let r = find_tag_offset(&p, b"rTRC").unwrap();
        let g = find_tag_offset(&p, b"gTRC").unwrap();
        let b = find_tag_offset(&p, b"bTRC").unwrap();
        assert_eq!(r, g);
        assert_eq!(g, b);
    }

    #[test]
    fn output_is_bit_stable_across_calls() {
        // Byte-identical profile across builds.
        let a = cineon_log_profile(ColorEncoding::ProPhotoRgb).unwrap();
        let b = cineon_log_profile(ColorEncoding::ProPhotoRgb).unwrap();
        assert_eq!(a, b);
    }
}
